[project]
name = "LIBRARY_MANAGEMENT_SYSTEM"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Mohamed",email = "mohamedahamedassane@gmail.com"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
